runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/push-handlers/.*
  script: push.app
  login: admin
- url: /__.*__
  script: dockerflow.app
- url: .*
  script: edge.app

libraries:
- name: flask
  version: '0.12'
- name: ujson
  version: latest

env_variables:
  BIGQUERY_DATASET: telemetry
  NUM_RETRIES: 3
  EDGE_SCHEMA_FILES: '{"main":"schemas/main.4.schema.json"}'
  BIGQUERY_SCHEMA_FILES: '{"main":"schemas/main.4.bigquery.json"}'
