service: telemetry-example
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/push-handlers/bigquery/.*
  script: telemetry_example.bigquery.app
  login: admin
  secure: always
- url: /_ah/push-handlers/validate/.*
  script: telemetry_example.validate.app
  login: admin
  secure: always
- url: /__.*__
  script: telemetry_example.dockerflow.app
- url: /.*
  script: telemetry_example.edge.app

libraries:
- name: flask
  version: '0.12'
- name: ujson
  version: latest

skip_files:
# defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# custom
- default/
- requirements.txt
- scripts/
- test/

env_variables:
## for gcp api
  NUM_RETRIES: 3
## for telemetry_example.edge.app
  EDGE_TOPICS: '{"main_ping":"main_ping_raw","id_ping":"id_ping_raw"}'
## for telemetry_example.validate.app
  VALIDATE_SCHEMAS: '{"main_ping":"schemas/main.4.schema.json","id_ping":"schemas/id.schema.json"}'
  GEOIP2_DATABASE: GeoLite2-Country.mmdb
# TOPICS_IF_INVALID: '{"main_ping": "main_ping_invalid"}'
## for telemetry_example.bigquery.app
  BIGQUERY_DATASET: telemetry_example
  BIGQUERY_SCHEMA_FILES: '{"main_ping":"schemas/main.4.bigquery.json","id_ping":"schemas/id.bigquery.json"}'
