service: telemetry-example
runtime: python27
api_version: 1
threadsafe: yes

handlers:
## replaced by dataflow
# - url: /_ah/push-handlers/.*
#   script: telemetry_example.push.app
#   login: admin
#   secure: always
- url: /__.*__
  script: telemetry_example.dockerflow.app
- url: .*
  script: telemetry_example.edge.app

libraries:
- name: flask
  version: '0.12'
- name: ujson
  version: latest

skip_files:
# defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# custom
- default/
- requirements.txt
- scripts/
- test/

env_variables:
## for gcp api
  NUM_RETRIES: 3
## for telemetry_example.edge.app
  EDGE_SCHEMA_FILES: '{"main_ping":"schemas/main.4.schema.json"}'
  GEOIP2_DATABASE: GeoLite2-Country.mmdb
## for telemetry_example.push.app
# BIGQUERY_DATASET: telemetry_example
# BIGQUERY_SCHEMA_FILES: '{"main_ping":"schemas/main.4.bigquery.json"}'
