service: bigquery
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/push-handlers/bigquery/.*
  script: bigquery.app
  login: admin
  secure: always
- url: /__.*__
  script: dockerflow.app

libraries:
- name: flask
  version: '0.12'
- name: ujson
  version: latest

env_variables:
  NUM_RETRIES: 3
  BIGQUERY_DATASET: telemetry_example
  BIGQUERY_SCHEMA_FILES: '{"main_ping":"schemas/main.4.bigquery.json","id_ping":"schemas/id.bigquery.json"}'
